services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: abroad_db
      POSTGRES_USER: tomsaji
      POSTGRES_PASSWORD: tomsaji123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tomsaji -d abroad_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=True
      - DB_NAME=abroad_db
      - DB_USER=tomsaji
      - DB_PASSWORD=tomsaji123
      - DB_HOST=db
      - DB_PORT=5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tomsaji20@gmail.com  # Replace with your email
      PGADMIN_DEFAULT_PASSWORD: tomsaji123  # Replace with your password
    ports:
      - "5050:80"  # Expose pgAdmin on localhost:5050
    depends_on:
      - db

volumes:
  postgres_data: