# Generated by Django 5.1.6 on 2025-04-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('stream', models.CharField(max_length=50)),
                ('preferred_courses', models.TextField()),
                ('preferred_countries', models.TextField()),
                ('marks_12th', models.FloatField()),
            ],
        ),
    ]
