# Generated by Django 5.1.6 on 2025-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stream',
            field=models.CharField(choices=[('Science - Biology', 'Science Stream - Biology'), ('Science - Computer', 'Science Stream - Computer'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=50),
        ),
    ]
