# Generated by Django 5.1.6 on 2025-04-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad_app', '0002_alter_student_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, choices=[('Science - Biology', 'Science Stream - Biology'), ('Science - Computer', 'Science Stream - Computer'), ('Commerce', 'Commerce'), ('Humanities', 'Humanities')], max_length=50, null=True)),
                ('basic_requirements', models.TextField()),
                ('minimum_marks', models.FloatField()),
                ('ielts_score', models.FloatField()),
            ],
        ),
    ]
