# Generated by Django 5.1.6 on 2025-04-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad_app', '0004_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.IntegerField(default=200000),
        ),
    ]
