# Generated by Django 5.1.6 on 2025-04-04 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad_app', '0005_course_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fees', models.FloatField()),
                ('amount_paid', models.FloatField()),
                ('payment_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abroad_app.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abroad_app.student')),
            ],
        ),
    ]
