# Generated by Django 5.1.6 on 2025-04-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad_app', '0006_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='student_custom_id',
            field=models.CharField(default=0, editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
